"""init

Revision ID: 4ce8827a239e
Revises: 8c24c9d90769
Create Date: 2018-11-09 13:19:49.776255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ce8827a239e'
down_revision = '8c24c9d90769'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['email'], ['user_info.email'], name=op.f('fk_roles_email_user_info')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    # ### end Alembic commands ###
