"""init

Revision ID: 683f3a7c01a9
Revises: c75316d85d29
Create Date: 2018-11-13 13:12:51.374317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '683f3a7c01a9'
down_revision = 'c75316d85d29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
