"""init

Revision ID: 9991103954b4
Revises: 82f6b7d93c0c
Create Date: 2018-10-31 10:28:48.317374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9991103954b4'
down_revision = '82f6b7d93c0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_info',
    sa.Column('first_name', sa.Text(length=50), nullable=False),
    sa.Column('last_name', sa.Text(length=50), nullable=False),
    sa.Column('password', sa.Text(length=15), nullable=False),
    sa.Column('email', sa.Text(length=50), nullable=False),
    sa.Column('contact', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.Text(length=80), nullable=True),
    sa.Column('company_url', sa.Text(length=50), nullable=True),
    sa.Column('addline1', sa.Text(length=50), nullable=True),
    sa.Column('addline2', sa.Text(length=50), nullable=True),
    sa.Column('city', sa.Text(length=25), nullable=True),
    sa.Column('state', sa.Text(length=25), nullable=True),
    sa.Column('country', sa.Text(length=25), nullable=True),
    sa.Column('zipcode', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('email', name=op.f('pk_user_info')),
    sa.UniqueConstraint('email', name=op.f('uq_user_info_email'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_info')
    # ### end Alembic commands ###
